# Python 3.8.10
name: py38
channels:
  - conda-forge
  - defaults
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - blas=1.0=mkl
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py38hd3f51b4_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h4cb3324_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cpuonly=2.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h09e9e62_13
  - cudnn=8.9.7.29=he6de189_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - dlib=19.24.6=cuda118py38had58105_0
  - double-conversion=3.3.1=he0c23c2_0
  - ffmpeg=6.1.2=gpl_h63b3451_706
  - filelock=3.16.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.53.1=py38h4cb3324_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=11.4.5=h5f2951f_0
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_0
  - imath=3.1.12=hbb528cf_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.5=py38hb1fd069_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20240116.2=cxx17_he0c23c2_1
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libclang13=21.1.5=default_ha2db4b5_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.84.3=h1c1036b_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=12_h13b7882_netlib
  - liblapacke=3.9.0=12_h1360930_netlib
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libopencv=4.10.0=qt6_py38hfadb1d8_603
  - libopenvino=2024.3.0=hfe1841e_0
  - libopenvino-auto-batch-plugin=2024.3.0=h04f32e0_0
  - libopenvino-auto-plugin=2024.3.0=h04f32e0_0
  - libopenvino-hetero-plugin=2024.3.0=h372dad0_0
  - libopenvino-intel-cpu-plugin=2024.3.0=hfe1841e_0
  - libopenvino-intel-gpu-plugin=2024.3.0=hfe1841e_0
  - libopenvino-ir-frontend=2024.3.0=h372dad0_0
  - libopenvino-onnx-frontend=2024.3.0=hdeef14f_0
  - libopenvino-paddle-frontend=2024.3.0=hdeef14f_0
  - libopenvino-pytorch-frontend=2024.3.0=he0c23c2_0
  - libopenvino-tensorflow-frontend=2024.3.0=h7c40eac_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he0c23c2_0
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=4.25.3=h47a098d_1
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libuv=1.51.0=hfd05255_1
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h2466b09_2
  - libzlib-wapi=1.2.13=h2466b09_6
  - llvm-openmp=20.1.8=h29ce207_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.5=py38h91455d4_0
  - matplotlib-base=3.7.3=py38h2724991_0
  - mkl=2023.1.0=h6a75c08_48682
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.24.4=py38h1d91fd2_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.10.0=qt6_py38ha3d2b97_603
  - openexr=3.2.2=h9aba623_2
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py38hf08cf0d_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.45=h99c9b8b_0
  - pillow=10.4.0=py38h8d10685_0
  - pip=24.2=py38haa95532_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - psutil=6.0.0=py38h4cb3324_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pugixml=1.14=h63175ca_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - py-opencv=4.10.0=qt6_py38h8ff50eb_603
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.20=hfaddaf0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytorch=2.4.1=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h4cb3324_0
  - qt6-main=6.8.3=h02ddd7d_4
  - requests=2.32.3=pyhd8ed1ab_0
  - scipy=1.10.1=py38h1aea9ed_3
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=75.1.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.2=h7fa0ca8_0
  - sqlite=3.50.2=hda9a48d_1
  - statsmodels=0.14.1=py38he7056a7_0
  - svt-av1=2.3.0=he0c23c2_0
  - sympy=1.13.3=pyh04b8f61_4
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.13=h2c6b04d_2
  - torchvision=0.19.1=py38_cpu
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - ucrt=10.0.22621.0=haa95532_0
  - ultralytics=8.3.43=pyh101cb37_0
  - unicodedata2=15.1.0=py38h91455d4_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstandard=0.19.0=py38h91455d4_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - dill==0.4.0
      - faker==35.2.2
      - intel-cmplr-lib-ur==2025.3.1
      - intel-openmp==2025.3.1
      - lap==0.5.12
      - tcmlib==1.4.1
      - typing-extensions==4.13.2
      - umf==1.0.2
prefix: D:\Program\miniconda3\envs\py38
